# Generated by Django 3.0.8 on 2021-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_databaseuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSatisfactionSurvey',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('how_satisfied', models.CharField(max_length=64)),
                ('trying_to_do', models.TextField(blank=True, null=True)),
                ('improve_service', models.TextField(blank=True, null=True)),
            ],
            options={'abstract': False},
        ),
    ]
